array_layout = "Block"
closure_block_indent_threshold = 2
fn_args_layout = "Block"
fn_call_style = "Block"
fn_empty_single_line = false
fn_single_line = true
format_strings = true
generics_indent = "Block"
match_block_trailing_comma = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
use_try_shorthand = true
where_pred_indent = "Block"
where_style = "Rfc"
wrap_match_arms = false
